### ISSUE TITLE
Songs not downloading

### ISSUE THREAD

**Issue by Monose** [rithik-b/MorePlaylists#7]
I've found 3 different playlists that I'd like to download and whenever I click the download playlist + songs button it will start the download, say it's completed, but then none of the songs are in my library. I double-checked to make sure I have the necessary mods downloaded in order for this one to function and I do. I've tried uninstalling and reinstalling all mods to try and get it to work properly but that didn't work either.

**Comment by rithik-b** [comment]
Please be patient, all mods need to migrate to the new BeatSaver, all updates for this will be given in the BSMG discord

**Comment by Arlithian** [comment]
Came to report the same, will keep an eye out - keep up the good work!
